### ISSUE TITLE
true xor (not false) == true

### ISSUE THREAD

**Issue by riwu** [SRL/Lape#15] opened 2015-09-22 10:34 UTC
```
var
  aTruthfulBool: boolean;
begin
  writeln(true xor (not false));
  aTruthfulBool:= not false;
  writeln(true xor aTruthfulBool);
  writeln(true = aTruthfulBool);
end.   
```

result: all returned true.
Any idea which files i should be looking at to find out the cause of this?

**Comment by nielsAD** [comment] 2015-09-22 12:11
The problem is that `not false` is not returning 1 (true) for its integer representation, because they are evaluated as integer expressions in the background. Thanks for reporting!

**Comment by nielsAD** [comment] 2015-12-23 15:12
https://github.com/nielsAD/lape/pull/53
Fixed by @WarPie :)

**Closed by nielsAD** 2015-12-23 15:13 UTC
